#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

name: NEW Make Tailscale run files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fetch latest release tag from Tailscale
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/whzhni1/luci-app-tailscale/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest Tailscale files
        run: |
          mkdir -p downloads
          cd downloads

          # 下载 x86_64 ipk
          curl -L -O $(
            curl -s https://api.github.com/repos/whzhni1/luci-app-tailscale/releases/latest \
            | jq -r '.assets[] | select(.name | test("tailscale.*.ipk")) | .browser_download_url'
          )

          # 下载 aarch64_cortex-a53 ipk
          curl -L -O $(
            curl -s https://api.github.com/repos/whzhni1/luci-app-tailscale/releases/latest \
            | jq -r '.assets[] | select(.name | test("tailscale.*.ipk")) | .browser_download_url'
          )


          # 下载luci app ipk
          curl -L -O $(
            curl -s https://api.github.com/repos/whzhni1/luci-app-tailscale/releases/latest \
            | jq -r '.assets[] | select(.name | test("luci-.*-tailscale.*\\.ipk")) | .browser_download_url' | head -1
          )
          # 下载luci语言包ipk
          curl -L -O $(
            curl -s https://api.github.com/repos/whzhni1/luci-app-tailscale/releases/latest \
            | jq -r '.assets[] | select(.name | test("luci-.*-tailscale-zh-cn.*\\.ipk")) | .browser_download_url' | tail -1
          )


      - name: Organize files for x86_64
        run: |
          mkdir -p tailscale_x86_64/depends tailscale_x86_64/main
          cp downloads/luci-*.ipk tailscale_x86_64/main/
          cp downloads/tailscale.*.x86_64.ipk tailscale_x86_64/depends/

      - name: Organize files for aarch64_cortex-a53
        run: |
          mkdir -p tailscale_aarch64/depends tailscale_aarch64/main
          cp downloads/luci-*.ipk tailscale_aarch64/main/
          cp downloads/tailscale.*.aarch64_cortex-a53.ipk tailscale_aarch64/depends/

      - name: Create install.sh scripts
        run: |
          cat <<EOF > tailscale_x86_64/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install depends/*.ipk
          opkg install main/*.ipk
          EOF
          chmod +x tailscale_x86_64/install.sh
          cp tailscale_x86_64/install.sh tailscale_aarch64/install.sh

      - name: Move tailscale directories to makeself
        run: |
          mv tailscale_x86_64 makeself/
          mv tailscale_aarch64 makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh tailscale_x86_64/ tailscale_x86_64_${{ env.LATEST_TAG }}.run "by github action" ./install.sh
          ./makeself.sh tailscale_aarch64/ tailscale_aarch64_a53_${{ env.LATEST_TAG }}.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/tailscale*.run

      - name: Preparing release name
        run: |
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      - name: Fetch latest release details
        id: fetch_release_details
        run: |
          extra_content="![Github](https://img.shields.io/badge/Tailscale.run-123456?logo=github&logoColor=fff&labelColor=green&style=for-the-badge) [![Github](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.cn/archives/1) ![GitHub Downloads (all assets, specific tag)](https://img.shields.io/github/downloads/wukongdaily/RunFilesBuilder/${{ env.LATEST_TAG }}/total?style=for-the-badge&labelColor=black&color=%2325c2a0)"
          release_notes=$(curl -s https://api.github.com/repos/whzhni1/luci-app-tailscale/releases/latest | jq -r '.body')
          if [ -z "$release_notes" ]; then
            release_notes="No release notes available."
          fi
          echo -e "$extra_content\n\n$release_notes" > release_notes.md

      - name: Print release notes
        run: |
          cat release_notes.md

      - name: Generate new tag & release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LATEST_TAG }}
          target_commitish: ${{ github.ref_name }}
          prerelease: false
          body_path: release_notes.md

      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ env.LATEST_TAG }}
          name: "Tailscale-${{ env.LATEST_TAG }}"
          files: makeself/tailscale*.run
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
